version: '3.8'

services:
  postgres:
    image: postgres:15.4-alpine3.17
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: my_local_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
